# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode
development:
  <<: *default
  database: sherbim_development

test:
  <<: *default
  database: sherbim_test
  host: localhost

production:
  <<: *default
  database: sherbim_production
