# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
development:
  <<: *default
  encoding: unicode
  database: sherbim_development
  host: localhost
  username: <%= ENV['POSTGREUSER'] %>
  password: <%= ENV['POSTGREPASS'] %>

test:
  <<: *default
  encoding: unicode
  database: sherbim_test
  host: localhost
  username: <%= ENV['POSTGREUSER'] %>
  password: <%= ENV['POSTGREPASS'] %>